---
title: "R Notebook"
output: html_notebook
---

##Goal of collecting this dataset
The goal of collecting this dataset is to determine the category of a given vehicle silhouette among three types (car, van, bus) by utilizing a set of extracted silhouette-based features.

##Classification
The classification of vehicle silhouettes involves the utilization of a set of distinctive attributes extracted from these silhouettes. The primary objective is to categorize these silhouettes into one of three predefined classes: cars, vans, or buses.

##Defect prediction
Defect prediction in a dataset of vehicle silhouettes involves spotting potential issues or irregularities within these silhouette images. This process may encompass the detection of inconsistencies or abnormalities in the silhouettes, including the presence of missing data points, which can be problematic. Leveraging data mining techniques, defect prediction enhances the dataset's overall quality and dependability, ensuring it faithfully reflects the desired information. This, in turn, reduces the risk of producing inaccurate or deceptive outcomes when the dataset is applied in subsequent tasks and applications, such as object recognition and classification.

##Link Of dataset:
https://www.kaggle.com/datasets/pritech/vehicle-silhouettes/data

##Number of attribute
19
##Number of objects
847
```{r}

##read file named "vehicle.csv" and save it in dataframe named "dataset"
dataset=read.csv("C:/Users/Tshah/OneDrive/Desktop/326/project/vehicle.csv")
str(dataset)
```

Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Ctrl+Alt+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Ctrl+Shift+K* to preview the HTML file).

The preview shows you a rendered HTML copy of the contents of the editor. Consequently, unlike *Knit*, *Preview* does not run any R code chunks. Instead, the output of the chunk when it was last run in the editor is displayed.
